version: '3'

services:
  pgdb:
    image: postgres
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  
  django:
    build: .
    container_name: django    
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - pgdb

volumes:
  pgdbdata: null